version: 2
registries:
  git-github-com:
    type: git
    url: https://github.com
    username: x-access-token
    password: "${{secrets.GIT_GITHUB_COM_PASSWORD}}"

updates:
- package-ecosystem: composer
  directory: "/"
  schedule:
    interval: daily
    time: "10:00"
  open-pull-requests-limit: 20
  ignore:
  - dependency-name: vimeo/psalm
    versions:
    - 4.4.0
    - 4.5.0
    - 4.6.0
  registries:
  - git-github-com
