language: php
dist: trusty
sudo: false

cache:
  directories:
    - $HOME/.composer/cache
    - vendor

before_install:
  - phpenv config-rm xdebug.ini || true

php:
  - 7.1
  - 7.2
  - 7.3

matrix:
  fast_finish: true

install:
  - composer install --no-interaction --no-progress --prefer-dist --ansi

script:
  - composer cs-check
  - composer static-analysis
  - composer test

jobs:
    include:
        - stage: Coverage
          env: COVERAGE
          before_script:
            - phpenv config-add xdebug.ini
            - if [[ ! $(php -m | grep -si xdebug) ]]; then echo "xdebug required for coverage"; exit 1; fi
          script:
            - ./vendor/bin/phpunit --coverage-clover clover.xml
          after_script:
            - wget https://scrutinizer-ci.com/ocular.phar
            - php ocular.phar code-coverage:upload --format=php-clover clover.xml
